module.exports = {
  name: 'track-game-state',
  xcoord: 474.04429999999996,
  ycoord: 480.6236,
  direction: 48.06236,
  zone: '0\u0006\u0017\u0010F6',
  corpseX: 167.70971,
  corpseY: 165.75934,
  processExitStatus: true,
  needManaGem: true,
  targetOfTargetIsPlayer: true,
  playerInCombat: false,
  spell: {
    drinkWater: {
      active: true,
    },
    evocation: {
      active: true,
    },
    iceBarrier: {
      active: true,
    },
    arcaneIntellect: {
      active: true,
    },
    frostArmor: {
      active: true,
    },
    eatFood: {
      active: true,
    },
  },
  needFood: true,
  needWater: true,
  flying: true,
  itemsAreBroken: true,
  talentPoints: true,
  deadStatus: true,
  targetIsDead: true,
  targetInCombat: true,
  healthMax: 16250871,
  healthCurrent: 16053750,
  health: 98.78701270842653,
  manaMax: 16250871,
  manaCurrent: 5003615,
  mana: 30.78982658837179,
  energyMax: 4937822,
  energyCurrent: 4937822,
  energy: 100,
  comboPoints: 5003615,
  level: 5003615,
  range: 4937822,
  target: '2\u0003=2\u0003=',
  targetHealth: 5003615,
  spells: {
    bloodrage: {
      castable: false,
      equipped: true,
      notEnoughMana: true,
      spellInRange: true,
    },
    moonfire: {
      castable: true,
      equipped: true,
      notEnoughMana: true,
      spellInRange: true,
    },
    fireball: {
      castable: false,
      equipped: false,
      notEnoughMana: false,
      spellInRange: false,
    },
    sinisterStrike: {
      castable: false,
      equipped: false,
      notEnoughMana: false,
      spellInRange: false,
    },
    frostNova: {
      castable: false,
      equipped: false,
      notEnoughMana: false,
      spellInRange: false,
    },
    eatFood: {
      castable: true,
      equipped: true,
      notEnoughMana: true,
      spellInRange: true,
    },
    drinkWater: {
      castable: true,
      equipped: true,
      notEnoughMana: true,
      spellInRange: true,
    },
    slot8: {
      castable: false,
      equipped: false,
      notEnoughMana: false,
      spellInRange: false,
    },
    evocation: {
      castable: false,
      equipped: true,
      notEnoughMana: true,
      spellInRange: true,
    },
    manaShield: {
      castable: false,
      equipped: false,
      notEnoughMana: false,
      spellInRange: false,
    },
    counterspell: {
      castable: true,
      equipped: true,
      notEnoughMana: true,
      spellInRange: true,
    },
    slot12: {
      castable: true,
      equipped: true,
      notEnoughMana: true,
      spellInRange: true,
    },
    conjureFood: {
      castable: true,
      equipped: true,
      notEnoughMana: true,
      spellInRange: true,
    },
    conjureWater: {
      castable: false,
      equipped: false,
      notEnoughMana: false,
      spellInRange: false,
    },
    frostArmor: {
      castable: true,
      equipped: true,
      notEnoughMana: true,
      spellInRange: true,
    },
    arcaneIntellect: {
      castable: false,
      equipped: false,
      notEnoughMana: false,
      spellInRange: false,
    },
    blink: {
      castable: true,
      equipped: false,
      notEnoughMana: false,
      spellInRange: false,
    },
    conjureGem: {
      castable: true,
      equipped: false,
      notEnoughMana: false,
      spellInRange: false,
    },
    consumeGem: {
      castable: true,
      equipped: false,
      notEnoughMana: false,
      spellInRange: false,
    },
    iceBarrier: {
      castable: true,
      equipped: false,
      notEnoughMana: false,
      spellInRange: false,
    },
    slot69: {
      castable: false,
      equipped: true,
      notEnoughMana: true,
      spellInRange: true,
    },
    hearthstone: {
      castable: false,
      equipped: false,
      notEnoughMana: false,
      spellInRange: false,
    },
    slot71: {
      castable: true,
      equipped: true,
      notEnoughMana: true,
      spellInRange: true,
    },
    slot72: {
      castable: false,
      equipped: false,
      notEnoughMana: false,
      spellInRange: false,
    },
  },
  id: 0,
};
