const {
  bloodthirst,
  desperatePrayer,
  rejuvenation,
  riptide,
  waterShield,
  sinisterStrike,
  slow,
  eviscerate,
  innerFire,
  heroicStrike,
  kidneyShot,
  execute,
  fortitude,
  pull,
} = require('../actions');
const goals = require('../goals');

module.exports = {
  mapping: {
    bloodthirst: 'b',
    desperatePrayer: 'g',
    rejuvenation: 'a',
    riptide: '9',
    waterShield: '7',
    sinisterStrike: '5',
    slow: '8',
    eviscerate: '6',
    heroicStrike: '4',
    execute: 'w',
    fortitude: 'y',
    kidneyShot: 't',
    innerFire: 'q',
    pull: '0',
  },
  actions: {
    bloodthirst,
    desperatePrayer,
    rejuvenation,
    riptide,
    waterShield,
    kidneyShot,
    sinisterStrike,
    slow,
    eviscerate,
    innerFire,
    heroicStrike,
    execute,
    fortitude,
    pull,
  },
  overrides: {},
  goals,
};
